function dist = runSimulationCompanion(sma0,ecc0,inc0,raan0,aop0,aota0,timeVector,plotTimeVector)
approximateOrbitalPeriod = 2*pi*sqrt(sma0^3/Consts.mu);
followerIntialDeltaFromLeaderCOEinDeprit = {0,0,0,0,0,pi/3};
COE0 = {sma0,ecc0,inc0,raan0,aop0,aota0};




odeEvents = {0};



S = cell(3,1);
dist = cell(numel(odeEvents),1);
bridgeFunctions = {@zeroMeanBridgeDeltaVector,@bridgeToDepritSpace,@zeroChangeBridge};
for index = 1:numel(bridgeFunctions)
    bridgeFunction = bridgeFunctions{index};
    
    satellitesVector = ...
        createLeaderAndFollowerSatelliteVector(...
        COE0,followerIntialDeltaFromLeaderCOEinDeprit,...
        bridgeFunction);

    numOfSatellites = length(satellitesVector);
    
    S{index} = propMultiSatelliteStateSpace(...
        satellitesVectorToODEInitialConditions(satellitesVector),...
        timeVector,...
        odeEvents{1},...
        StateSpaceEnum.J2);

    [PolarNodalsRealSpaceSimResults,PolarNodalsDepritSimResults] = ...
        extractPositionsFromSolutions(S{index},numOfSatellites,bridgeFunction);

    dist{index} = physicalDistanceFromPolarNodals(PolarNodalsRealSpaceSimResults{1}, ...
        PolarNodalsRealSpaceSimResults{2});

    % plot(plotTimeVector, dist{index}-dist{index}(1))
    % hold on
end
% title("distance over time")
% ylabel("distance [km]")
% xlabel("approximate orbit ")
% legend("New Generating Function", "Old Generating Function", "Naive Placement")
% xline(0:max(int32(timeVector/approximateOrbitalPeriod)))

COERealSpaceSimResults = ...
    cellfun(...
    @(pos) ...
    convertCoordinateSystem(pos,CoordinateSystemEnum.PN, ...
    CoordinateSystemEnum.COE), ...
    PolarNodalsRealSpaceSimResults, "UniformOutput",false ...
    );
[~, CEODepritSimResults] = ...
    cellfun(...
    @(pos) J2RealSpaceToAveragedSpace(pos,CoordinateSystemEnum.PN,bridgeFunction), ...
    PolarNodalsRealSpaceSimResults, "UniformOutput",false ...
    );



[PolarNodalsRealSpaceSimResults,PolarNodalsDepritSimResults] = ...
    cellfun(@(Sol) extractPositionsFromSolutions(Sol,numOfSatellites,bridgeFunction),...
    S, "UniformOutput", false);

dist = max(physicalDistanceFromPolarNodals( ...
    PolarNodalsRealSpaceSimResults{1}{2}, ...
    PolarNodalsRealSpaceSimResults{3}{2} ...
    ));


% plot(plotTimeVector,physicalDistanceFromPolarNodals( ...
%     PolarNodalsRealSpaceSimResults{1}{2}, ...
%     PolarNodalsRealSpaceSimResults{3}{2} ...
%     ))
end