function diff_Theta_star = diff_Theta_star_Func(Theta,Nu,mu,J2,Req)
%diff_Theta_star_Func
%    diff_Theta_star = diff_Theta_star_Func(r,THETA,NU,R,Theta,Nu,MU,J2,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    25-May-2023 15:07:50

t2 = Nu.^2;
t3 = Req.^2;
t4 = mu.^2;
t5 = 1.0./Theta.^2;
t6 = t2.*t5.*3.0;
t7 = t6-1.0;
diff_Theta_star = (1.0./sqrt(1.0./t5-(J2.*t3.*t4.*t5.*t7)./2.0).*(Theta.*2.0+J2.*1.0./Theta.^5.*t2.*t3.*t4.*3.0+J2.*1.0./Theta.^3.*t3.*t4.*t7))./2.0;
end
