function diff2_Theta_star = diff2_Theta_star_Func(Theta,Nu,mu,J2,Req)
%diff2_Theta_star_Func
%    diff2_Theta_star = diff2_Theta_star_Func(r,THETA,NU,R,Theta,Nu,MU,J2,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    25-May-2023 15:14:40

t2 = Nu.^2;
t3 = Theta.^2;
t4 = Req.^2;
t5 = mu.^2;
t6 = 1.0./t3;
t7 = t2.*t6.*3.0;
t8 = t7-1.0;
t9 = (J2.*t4.*t5.*t6.*t8)./2.0;
t10 = -t9;
t11 = t3+t10;
diff2_Theta_star = 1.0./t11.^(3.0./2.0).*(Theta.*2.0+J2.*1.0./Theta.^5.*t2.*t4.*t5.*3.0+J2.*1.0./Theta.^3.*t4.*t5.*t8).^2.*(-1.0./4.0)-(1.0./sqrt(t11).*(J2.*t2.*t4.*t5.*t6.^3.*2.1e+1+J2.*t4.*t5.*t6.^2.*t8.*3.0-2.0))./2.0;
end
