function diff_nu_star = diff_nu_star_Func()
%diff_nu_star_Func
%    DIFF_NU_STAR = diff_nu_star_Func(r,THETA,NU,R,Theta,Nu,MU,J2,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    25-May-2023 15:07:50

diff_nu_star = 1.0;
end
