function diff_theta_star = diff_s_theta_star_Func(Theta,Nu,mu,J2,alpha)
%diff_smalltheta_star_Func
%    DIFF_THETA_STAR = diff_smalltheta_star_Func(r,THETA,NU,R,Theta,Nu,MU,J2,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    25-May-2023 15:07:50

t2 = Nu.^2;
t3 = alpha.^2;
t4 = mu.^2;
t5 = 1.0./Theta.^2;
t6 = t2.*t5.*3.0;
t7 = t6-1.0;
diff_theta_star = (sqrt(1.0./t5-(J2.*t3.*t4.*t5.*t7)./2.0).*2.0)./(Theta.*2.0+J2.*1.0./Theta.^5.*t2.*t3.*t4.*3.0+J2.*1.0./Theta.^3.*t3.*t4.*t7);
end
