function diff2_theta_star = diff2_s_theta_star_Func(r,theta,nu,R,Theta,Nu,mu,J2,alpha)
%diff2_s_theta_star_Func
%    DIFF2_THETA_STAR = diff2_s_theta_star_Func(r,THETA,NU,R,Theta,Nu,MU,J2,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    25-May-2023 15:14:40

diff2_theta_star = 0.0;
end
