function nu_star = nu_star_Func(theta,nu,Theta,Nu,mu,J2,Req)
%nu_star_Func
%    NU_STAR = nu_star_Func(r,THETA,NU,R,Theta,Nu,MU,J2,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    25-May-2023 15:10:48

t2 = Nu.^2;
t3 = Theta.^2;
t5 = Req.^2;
t6 = mu.^2;
t4 = t3.^3;
nu_star = (nu.*t4.*2.0+J2.*nu.*t2.*t5.*t6.*6.0-J2.*nu.*t3.*t5.*t6+J2.*Nu.*Theta.*t5.*t6.*theta.*3.0)./(t4.*2.0+J2.*t2.*t5.*t6.*6.0-J2.*t3.*t5.*t6);
end
