function theta_star = s_theta_star_Func(theta,Theta,Nu,mu,J2,Req)
%s_theta_star_Func
%    THETA_STAR = s_theta_star_Func(r,THETA,NU,R,Theta,Nu,MU,J2,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    25-May-2023 15:10:48

t2 = Nu.^2;
t3 = Req.^2;
t4 = mu.^2;
t5 = 1.0./Theta.^2;
t6 = t2.*t5.*3.0;
t7 = t6-1.0;
theta_star = (theta.*sqrt(1.0./t5-(J2.*t3.*t4.*t5.*t7)./2.0).*2.0)./(Theta.*2.0+J2.*1.0./Theta.^5.*t2.*t3.*t4.*3.0+J2.*1.0./Theta.^3.*t3.*t4.*t7);
end
