function Theta_star = Theta_star_Func(Theta,Nu,mu,J2,Req)
%Theta_star_Func
%    Theta_star = Theta_star_Func(r,THETA,NU,R,Theta,Nu,MU,J2,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    25-May-2023 15:10:48

t2 = 1.0./Theta.^2;
Theta_star = sqrt(1.0./t2-(J2.*Req.^2.*mu.^2.*t2.*(Nu.^2.*t2.*3.0-1.0))./2.0);
end
