function depritHessian = depritHessian(t,in2,mu,J2,alpha)
%depritHessian
%    depritHessian = depritHessian(T,IN2,MU,J2,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    13-Dec-2025 14:31:39

Nu = in2(6,:);
Theta = in2(5,:);
r = in2(1,:);
t2 = Nu.^2;
t3 = alpha.^2;
t4 = 1.0./Theta.^2;
t5 = 1.0./Theta.^3;
t6 = 1.0./r.^3;
t7 = 1.0./r.^4;
t8 = Theta.*t6.*2.0;
t10 = J2.*Nu.*mu.*t3.*t5.*t6.*3.0;
t11 = J2.*Nu.*mu.*t3.*t4.*t7.*(9.0./2.0);
t12 = J2.*mu.*t2.*t3.*t5.*t7.*(9.0./2.0);
t9 = -t8;
t13 = -t12;
t14 = t9+t13;
depritHessian = reshape([mu.*t6.*-2.0+(t7.*3.0)./t4-J2.*mu.*1.0./r.^5.*t3.*(t2.*t4.*3.0-1.0).*3.0,in2(6,:).*0.0,0.0,in2(6,:).*0.0,t14,t11,in2(6,:).*0.0,0.0,in2(6,:).*0.0,0.0,in2(6,:).*0.0,0.0,in2(6,:).*0.0,0.0,in2(6,:).*0.0,0.0,in2(6,:).*0.0,0.0,in2(6,:).*0.0,0.0,in2(6,:).*0.0,1.0,in2(6,:).*0.0,0.0,t14,in2(6,:).*0.0,0.0,in2(6,:).*0.0,1.0./r.^2-J2.*mu.*t2.*t3.*t4.^2.*t6.*(9.0./2.0),t10,t11,in2(6,:).*0.0,0.0,in2(6,:).*0.0,t10,J2.*mu.*t3.*t4.*t6.*(-3.0./2.0)],[6,6]);
end
