function depritHamiltonianGradient = depritGradient(t,in2,mu,J2,alpha)
%depritGradient
%    depritHamiltonianGradient = depritGradient(T,IN2,MU,J2,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    13-Dec-2025 14:31:39

Nu = in2(6,:);
R = in2(4,:);
Theta = in2(5,:);
r = in2(1,:);
t2 = Nu.^2;
t3 = alpha.^2;
t4 = 1.0./Theta.^2;
t5 = 1.0./r.^2;
t6 = 1.0./r.^3;
depritHamiltonianGradient = [mu.*t5-t6./t4+J2.*mu.*t3.*t5.^2.*(t2.*t4.*3.0-1.0).*(3.0./4.0);in2(6,:).*0.0;0.0;R;Theta.*t5+J2.*1.0./Theta.^3.*mu.*t2.*t3.*t6.*(3.0./2.0);J2.*Nu.*mu.*t3.*t4.*t6.*(-3.0./2.0)];
end
