function j2Hessian = j2Hessian(t,in2,mu,J2,alpha)
%j2Hessian
%    j2Hessian = j2Hessian(T,IN2,MU,J2,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    13-Dec-2025 14:31:39

Nu = in2(6,:);
Theta = in2(5,:);
r = in2(1,:);
theta = in2(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = Nu.^2;
t5 = alpha.^2;
t7 = 1.0./Theta.^2;
t8 = 1.0./Theta.^3;
t9 = 1.0./r.^3;
t10 = 1.0./r.^4;
t6 = t3.^2;
t11 = Theta.*t9.*2.0;
t13 = t4.*t7;
t15 = J2.*Nu.*mu.*t2.*t3.*t5.*t7.*t9.*6.0;
t19 = J2.*mu.*t2.*t3.*t4.*t5.*t8.*t9.*6.0;
t12 = -t11;
t14 = t13-1.0;
t16 = J2.*Nu.*mu.*t5.*t6.*t8.*t9.*6.0;
t17 = -t15;
t18 = J2.*Nu.*mu.*t5.*t6.*t7.*t10.*9.0;
t20 = J2.*mu.*t4.*t5.*t6.*t8.*t10.*9.0;
t21 = -t20;
t22 = J2.*mu.*t2.*t3.*t5.*t10.*t14.*9.0;
t23 = t12+t21;
j2Hessian = reshape([mu.*t9.*-2.0+(t10.*3.0)./t7-J2.*mu.*1.0./r.^5.*t5.*(t6.*t14.*3.0+1.0).*6.0,t22,in2(6,:).*0.0,0.0,t23,t18,t22,J2.*mu.*t2.^2.*t5.*t9.*t14.*-3.0+J2.*mu.*t5.*t6.*t9.*t14.*3.0,in2(6,:).*0.0,0.0,t19,t17,in2(6,:).*0.0,0.0,in2(6,:).*0.0,0.0,in2(6,:).*0.0,0.0,in2(6,:).*0.0,0.0,in2(6,:).*0.0,1.0,in2(6,:).*0.0,0.0,t23,t19,in2(6,:).*0.0,0.0,1.0./r.^2-J2.*mu.*t5.*t6.*t7.*t9.*t13.*9.0,t16,t18,t17,in2(6,:).*0.0,0.0,t16,J2.*mu.*t5.*t6.*t7.*t9.*-3.0],[6,6]);
end
