function keplerHamiltonianGradient = keplerGradient(t,in2,mu,J2,alpha)
%keplerGradient
%    keplerHamiltonianGradient = keplerGradient(T,IN2,MU,J2,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    13-Dec-2025 14:31:38

R = in2(4,:);
Theta = in2(5,:);
r = in2(1,:);
t2 = 1.0./r.^2;
keplerHamiltonianGradient = [mu.*t2-Theta.^2.*1.0./r.^3;in2(6,:).*0.0;0.0;R;Theta.*t2;in2(6,:).*0.0];
end
