function keplerHamiltonianHessian = keplerHessian(t,in2,mu,J2,alpha)
%keplerHessian
%    keplerHamiltonianHessian = keplerHessian(T,IN2,MU,J2,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    13-Dec-2025 14:31:39

Theta = in2(5,:);
r = in2(1,:);
t2 = 1.0./r.^3;
t3 = Theta.*t2.*2.0;
t4 = -t3;
keplerHamiltonianHessian = reshape([mu.*t2.*-2.0+Theta.^2.*1.0./r.^4.*3.0,in2(6,:).*0.0,0.0,in2(6,:).*0.0,t4,in2(6,:).*0.0,0.0,in2(6,:).*0.0,0.0,in2(6,:).*0.0,0.0,in2(6,:).*0.0,0.0,in2(6,:).*0.0,0.0,in2(6,:).*0.0,0.0,in2(6,:).*0.0,0.0,in2(6,:).*0.0,0.0,1.0,in2(6,:).*0.0,0.0,t4,in2(6,:).*0.0,0.0,in2(6,:).*0.0,1.0./r.^2,in2(6,:).*0.0,0.0,in2(6,:).*0.0,0.0,in2(6,:).*0.0,0.0,in2(6,:).*0.0],[6,6]);
end
