function [timeVector, PolarNodalsRealSpaceSimResults, S] = propagateAveragedSpace( ...
    initialConditions, initialConditionsCoordinateSystem, timeVector, eventFunctions)

[timeVector, PolarNodalsRealSpaceSimResults, S] = propagateStateSpace( ...
    initialConditions, initialConditionsCoordinateSystem, timeVector, eventFunctions, ...
    @(t,y) AveragedStateSpace_Func(t,y,Consts.mu,Consts.J2,Consts.Req));
end