function [timeVector, PolarNodalsRealSpaceSimResults, S] = propagateOsculatingSpace( ...
    initialConditions, initialConditionsCoordinateSystem, timeVector, eventFunctions)

[timeVector, PolarNodalsRealSpaceSimResults, S] = propagateStateSpace( ...
    initialConditions, initialConditionsCoordinateSystem, timeVector, eventFunctions, ...
    @(t,y) OsculatingStateSpace_Func(t,y,Consts.mu,Consts.J2,Consts.Req));
end