function [timeVector, PolarNodalsRealSpaceSimResults, S] = propagateJ2StateSpace( ...
    initialConditions, initialConditionsCoordinateSystem, timeVector, eventFunctions)

[timeVector, PolarNodalsRealSpaceSimResults, S] = propagateStateSpace( ...
    initialConditions, initialConditionsCoordinateSystem, timeVector, eventFunctions, ...
    @(t,y) j2StateSpace(t,y,Consts.mu,Consts.J2,Consts.Req));
end