function DeltaX = bridgeToDepritSpace(r,theta,nu,R,Theta,Nu,mu,J2,Req)
%DeltaXFunc
%    DeltaX = DeltaXFunc(r,THETA,NU,R,Theta,Nu,MU,J2,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    26-May-2023 17:05:49

t2 = Nu.^2;
t3 = Theta.^2;
t4 = Theta.^3;
t5 = Req.^2;
t6 = theta.*2.0;
t9 = 1.0./Theta.^5;
t10 = 1.0./r;
t7 = cos(t6);
t8 = sin(t6);
t11 = -t3;
t12 = t2+t11;
DeltaX = [(J2.*mu.*1.0./t3.^2.*t5.*(t2.*2.0+t12+t7.*t12))./4.0,...
    J2.*mu.*1.0./t3.^3.*t5.*t10.*(t3.^2.*t8.*4.0-R.*r.*t4.*4.0-t2.*t3.*t8.*1.2e+1-R.*r.*t4.*t7.*4.0+mu.*r.*t2.*t8.*5.0-mu.*r.*t3.*t8.*3.0+R.*Theta.*r.*t2.*2.4e+1+R.*Theta.*r.*t2.*t7.*8.0).*(-1.0./8.0),...
    (J2.*Nu.*mu.*t5.*t9.*t10.*(t3.*t8.*-4.0+R.*Theta.*r.*6.0+mu.*r.*t8+R.*Theta.*r.*t7.*2.0))./4.0,...
    (J2.*mu.*t5.*t8.*t10.^2.*t12.*(-1.0./2.0))./t4,...
    (J2.*mu.*t5.*t9.*t10.*(t7.*(Nu+Theta).*(Nu-Theta).*(t3.*4.0-mu.*r)+R.*Theta.*r.*t8.*t12.*2.0))./4.0,...
    zeros(size(r))];
end
