function satellitesVector = createLeaderAndFollowerSatelliteVector(COE0,followerIntialDeltaFromLeaderCOEinDeprit, bridgeFunction)
arguments (Input)
    COE0 (6,1)cell
    followerIntialDeltaFromLeaderCOEinDeprit(6,1)cell
    bridgeFunction function_handle
end

leader = Satellite(COE0,CoordinateSystemEnum.COE);

[~, COEsDepritKeplerianSpaceInitialConditions, ~] ...
    = J2RealSpaceToAveragedSpace(...
    leader.position,...
    leader.coordinateSystemEnum, ...
    bridgeFunction);

follower_COEsDepritKeplerianSpaceInitialConditions =...
    COEsDepritKeplerianSpaceInitialConditions;


for index = 1:Consts.numOfVarsInSS
    follower_COEsDepritKeplerianSpaceInitialConditions{index} ...
        = follower_COEsDepritKeplerianSpaceInitialConditions{index}...
        + followerIntialDeltaFromLeaderCOEinDeprit{index};
end
follower_PNInJ2RealSpaceInitialConditions =...
    KeplerianAveragedSpaceToJ2RealSpace(...
    follower_COEsDepritKeplerianSpaceInitialConditions, ...
    CoordinateSystemEnum.COE, ...
    bridgeFunction);


follower = Satellite(follower_PNInJ2RealSpaceInitialConditions,...
    CoordinateSystemEnum.PN);
satellitesVector = [leader,follower];
end