function [x,y,z,X,Y,Z] = PN2ECI(r,theta,nu,R,Theta,Nu)
%PN2ECI
%    [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6] = PN2ECI(r,THETA,NU,R,Theta,Nu)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    31-May-2023 10:56:23

t2 = cos(nu);
t3 = cos(theta);
t4 = sin(nu);
t5 = sin(theta);
t6 = Nu.^2;
t7 = 1.0./Theta;
t9 = 1.0./r;
t8 = t7.^2;
t10 = t2.*t3;
t11 = t3.*t4;
t13 = Nu.*t2.*t5.*t7;
t14 = Nu.*t4.*t5.*t7;
t12 = t6.*t8;
t17 = -t14;
t19 = t11+t13;
t15 = -t12;
t20 = t10+t17;
x = r.*t20;
if nargout > 1
    y = r.*t19;
end
if nargout > 2
    t16 = t15+1.0;
    t18 = sqrt(t16);
    z = r.*t5.*t18;
end
if nargout > 3
    X = R.*t20-Theta.*t9.*(t2.*t5+Nu.*t7.*t11);
end
if nargout > 4
    Y = R.*t19-Theta.*t9.*(t4.*t5-Nu.*t7.*t10);
end
if nargout > 5
    Z = R.*t5.*t18+Theta.*t3.*t9.*t18;
end
end
