function AveragedStateSpace = AveragedStateSpace_Func(~,y,mu,J2,alpha)
%AveragedStateSpace_Func
%    AveragedStateSpace = AveragedStateSpace_Func(~,y,mu,J2,alpha)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    25-May-2023 10:31:11

t2 = y(6).^2;
t3 = y(5).^2;
t5 = alpha.^2;
t6 = mu.^2;
t8 = 1.0./y(1).^2;
t4 = t3.^3;
t7 = 1.0./t3.^2;
t10 = J2.*t3.*t5.*t6;
t9 = t4.*2.0;
AveragedStateSpace = [y(4),...
    (1.0./y(5).^5.*t8.*(t9-t10+J2.*t2.*t5.*t6.*6.0))./2.0,...
    J2.*y(6).*t5.*t6.*t7.*t8.*(-3.0./2.0),...
    (1.0./y(1).^3.*t7.*(t9+t10-(mu.*y(1).*2.0)./t7-J2.*t2.*t5.*t6.*3.0))./2.0,...
    0.0,...
    0.0]';
end
