function j2StateSpace = j2StateSpace(~,in2,mu,J2,alpha)
%j2StateSpace
%    j2StateSpace = j2StateSpace(T,IN2,MU,J2,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    13-Dec-2025 14:31:38

Nu = in2(6,:);
R = in2(4,:);
Theta = in2(5,:);
r = in2(1,:);
theta = in2(2,:);
t2 = sin(theta);
t3 = Nu.^2;
t4 = alpha.^2;
t6 = 1.0./Theta.^2;
t7 = 1.0./r.^2;
t8 = 1.0./r.^3;
t5 = t2.^2;
t9 = t3.*t6;
t10 = t9-1.0;
j2StateSpace = [R;Theta.*t7+J2.*1.0./Theta.^3.*mu.*t3.*t4.*t5.*t8.*3.0;J2.*Nu.*mu.*t4.*t5.*t6.*t8.*-3.0;-mu.*t7+t8./t6-J2.*mu.*t4.*t7.^2.*(t5.*t10.*3.0+1.0).*(3.0./2.0);J2.*mu.*t2.*t4.*t8.*t10.*cos(theta).*3.0;in2(6,:).*0.0];
end
