function OsculatingStateSpace = OsculatingStateSpace_Func(~,y,mu,J2,Req)
%OsculatingStateSpace_Func
%    OsculatingStateSpace = OsculatingStateSpace_Func(t,y,mu,J2,Req)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    26-May-2023 14:56:51

t2 = sin(y(2,:));
t3 = y(6,:).^2;
t4 = Req.^2;
t6 = 1.0./y(5,:).^2;
t7 = 1.0./y(1,:).^3;
t5 = t2.^2;
t8 = t3.*t6.*3.0;
t9 = t8-3.0;
OsculatingStateSpace = [y(4,:);...
                        1.0./y(5,:).^3.*t7.*(y(1,:).*1.0./t6.^2+J2.*mu.*t3.*t4.*t5.*3.0);...
                        J2.*y(6,:).*mu.*t4.*t5.*t6.*t7.*-3.0;...
                        -mu.*1.0./y(1,:).^2+t7./t6-J2.*mu.*1.0./y(1,:).^4.*t4.*(t5.*t9+1.0).*(3.0./2.0);...
                        (J2.*mu.*t4.*t7.*t9.*sin(y(2,:).*2.0))./2.0;...
                        0.0*y(6,:)];
end
